# Generated by Django 3.1 on 2024-01-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
